# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
inhibit_all_warnings!
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ByteCal' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end

      target.shell_script_build_phases.each do |phase|
        next unless phase.name&.include?('[CP-User] [Hermes] Replace Hermes')

        if phase.output_paths.nil? || phase.output_paths.empty?
          phase.output_paths = ['$(DERIVED_FILE_DIR)/hermes-replace-stamp.txt']
        end

        unless phase.shell_script.include?('SCRIPT_OUTPUT_FILE_0')
          phase.shell_script = <<~SCRIPT
            #{phase.shell_script}
            echo "Hermes replaced at $(date)" > "${SCRIPT_OUTPUT_FILE_0}"
          SCRIPT
        end
      end
    end
  end
end
